import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/Header";
import { Footer } from "@/components/ui/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lumify | AI Powered Resume Enhancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` ${roboto.variable} antialiased flex min-h-screen w-full flex-col justify-between items-center align-center text-center`}
        >
          <Header />
          <div className="flex-grow w-full max-w-screen-xl">{children}</div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
